### ISSUE TITLE
error parsing metadata during upload

### ISSUE THREAD

**Issue by diraimondo** [thebigmunch/google-music-scripts#2] opened 2018-11-10 18:56 UTC
During the upload of my collection on GM I faced some issues:
```
Traceback (most recent call last):                                                                                                                                                                                   
  File "/home/mario/.virtualenvs/google-music/bin/gms", line 11, in <module>                                                                                                                                         
    sys.exit(gms())                                                                                                                                                                                                  
  File "/home/mario/.virtualenvs/google-music/lib/python3.7/site-packages/click/core.py", line 722, in __call__                                                                                                      
    return self.main(*args, **kwargs)
  File "/home/mario/.virtualenvs/google-music/lib/python3.7/site-packages/click/core.py", line 697, in main                                                                                                          
    rv = self.invoke(ctx)                                                                                                                                                                                            
  File "/home/mario/.virtualenvs/google-music/lib/python3.7/site-packages/click/core.py", line 1066, in invoke                                                                                                       
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                          
  File "/home/mario/.virtualenvs/google-music/lib/python3.7/site-packages/click/core.py", line 1066, in invoke                                                                                                       
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                          
  File "/home/mario/.virtualenvs/google-music/lib/python3.7/site-packages/click/core.py", line 895, in invoke                                                                                                        
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                                   
  File "/home/mario/.virtualenvs/google-music/lib/python3.7/site-packages/click/core.py", line 535, in invoke                                                                                                        
    return callback(*args, **kwargs)                                                                                                                                                                                 
  File "/home/mario/.virtualenvs/google-music/lib/python3.7/site-packages/google_music_scripts/commands/sync.py", line 215, in sync_up                                                                               
    local_songs, google_songs, fields=['artist', 'album', 'title', 'tracknumber'], normalize_values=True                                                                                                             
  File "/home/mario/.virtualenvs/google-music/lib/python3.7/site-packages/google_music_utils/compare.py", line 136, in find_missing_items                                                                            
    normalize_values=normalize_values, normalize_func=normalize_func                                                                                                                                                 
  File "/home/mario/.virtualenvs/google-music/lib/python3.7/site-packages/google_music_utils/compare.py", line 32, in _gather_field_values                                                                           
    item = audio_metadata.load(item).tags  # pragma: no cover                                                                                                                                                        
  File "/home/mario/.virtualenvs/google-music/lib/python3.7/site-packages/audio_metadata/api.py", line 44, in load                                                                                                   
    return parser_cls.load(fileobj)                                                                                                                                                                                  
  File "/home/mario/.virtualenvs/google-music/lib/python3.7/site-packages/audio_metadata/formats/mp3.py", line 477, in load                                                                                          
    self.streaminfo = MP3StreamInfo.load(self._obj)
  File "/home/mario/.virtualenvs/google-music/lib/python3.7/site-packages/audio_metadata/formats/mp3.py", line 372, in load
    samples_per_frame, _ = MP3SamplesPerFrame[(frames[0].version, frames[0].layer)]
IndexError: list index out of range
```

I guess it depends on the format of the metadata (maybe malformed). I was able to isolate an MP3 file that raise the issue: https://ufile.io/heni3

**Comment by thebigmunch** [comment] 2018-11-10 23:19
I can't seem to reproduce the error with this file. Either through using ``google-music-scripts`` or loading it with my ``audio-metadata`` library. Are you sure that file's one that is causing the error?

**Comment by thebigmunch** [comment] 2018-11-11 00:13
You can check files using ``audio-metadata`` directly (see the [docs](https://audio-metadata.readthedocs.io/en/stable/)). Or, use this [script](https://gist.github.com/thebigmunch/c80560c789ce72d46db301e15c265082) to load all supported files with ``audio-metadata`` in the directory it's run from recursively and print out filepaths it fails to load.

**Comment by thebigmunch** [comment] 2018-11-11 10:13
Still couldn't get the first one to error on my home machine (running Windows) even with a fresh virtualenv. I did run into the error with it on my seedbox (running Linux). And I can replicate the second file on my home machine. So, I'll investigate.

**Comment by thebigmunch** [comment] 2018-11-11 11:19
Thanks for reporting/helping with this.

If you're curious as to the cause, It's simply that I was using a different condition on an if check when reading MP3s that only show up in rare conditions when doing a ``peek()`` on a file didn't return enough data. The correct thing to do is to just check if there's any data at all. The files are perfectly fine.

I've got a new release of ``audio-metadata`` coming probably later today that will also include this fix. If you wanted to fix this issue in the meantime, you can just change [this line](https://github.com/thebigmunch/audio-metadata/blob/master/src/audio_metadata/formats/mp3.py#L352) to ``if not buffer:``.

**Comment by thebigmunch** [comment] 2018-11-11 12:37
For the files sent in the e-mail, I've only tested one of them. It seems to suffer from a big in older versions of LAME that wrote bad delay/padding for short files with low bitrate causing the sample calculation. All but 2 of the files you sent that aren't fixed by this fix appear to be suffering from that. I'm not sure what I'm going to do about it; I've kinda set forth the goal not to handle invalid files in ``audio-metadata``. I'll have to check the others that don't obviously fall under that bug to see what's wrong there.

**Comment by thebigmunch** [comment] 2018-11-11 15:08
Just as a note, mutagen's workaround for this sets the number of samples (used to calculate the song's duration) to 0 in this case, leaving the ``'length'`` property as 0.

I really don't like that. So, I'll probably add more exceptions to ``audio-metadata`` where needed and make their messages more useful. Then just catch them where needed up the chain, so this and other things can gracefully move past invalid files and report them to the user as needed.

**Closed** 2018-11-13 11:46 UTC
Labels: bug, solved, upstream
