### ISSUE TITLE
AttributeError: _size on any mp3

### ISSUE THREAD

**Issue by fooeynet** [thebigmunch/google-music-scripts#47] opened 2019-11-06 23:19 UTC
Can't seem to upload anything, tried multiple random mp3s and always get the following:

XXXXX@XXXXX01:~/music$ ~/.local/bin/gms upload --verbose k.mp3
[2019-11-06 15:13:25] Logging in to Music Manager
[2019-11-06 15:13:27] Logging in to Mobile Client
[2019-11-06 15:13:29] Loading local songs
[2019-11-06 15:13:29] Found 1 local songs
[2019-11-06 15:13:29] Comparing hashes
[2019-11-06 15:13:29] Loading Google songs with MobileClient
[2019-11-06 15:13:37] Found 15284 Google songs with MobileClient
Traceback (most recent call last):
  File "/home/XXXXX/.local/bin/gms", line 11, in <module>
    sys.exit(run())
  File "/home/XXXXX/.local/lib/python3.6/site-packages/google_music_scripts/cli.py", line 968, in run
    args.func(args)
  File "/home/XXXXX/.local/lib/python3.6/site-packages/google_music_scripts/commands.py", line 405, in do_upload
    if generate_client_id(song) not in google_client_ids:
  File "/home/XXXXX/.local/lib/python3.6/site-packages/google_music_proto/musicmanager/utils.py", line 30, in generate_client_id
    audio_start = song._id3._size
  File "/home/XXXXX/.local/lib/python3.6/site-packages/audio_metadata/structures.py", line 17, in __getattr__
    raise AttributeError(attr) from None
AttributeError: _size

**Comment by thebigmunch** [comment] 2019-11-07 00:13
Yeah, sorry. This is due to a version mismatch caused by a delay in a dependency release. I'll have it sorted out soonish.

**Comment by thebigmunch** [comment] 2019-11-07 00:17
In the meantime, you should be able to do ``pip install audio-metadata==0.6.0`` to get things running properly.

**Comment by thebigmunch** [comment] 2019-11-07 11:52
Should be fixed now.

**Closed by thebigmunch** 2019-11-07 11:52 UTC

**Comment by fooeynet** [comment] 2019-11-07 17:27
Hi!  No longer getting the previous error but now get a dependency on 3.7 (  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/concurrency/asyncio.py", line 63, in start_tls
    "asyncio.AbstractEventLoop.start_tls() is only available in Python 3.7+"
NotImplementedError: asyncio.AbstractEventLoop.start_tls() is only available in Python 3.7+)

Let me know if you'd rather this be its own issue.
---
 ~/.local/bin/gms upload --verbose waterphone-daniel_simon.mp3
[2019-11-07 09:25:00] Logging in to Music Manager
Traceback (most recent call last):
  File "/home/xxx/.local/bin/gms", line 11, in <module>
    sys.exit(run())
  File "/home/xxx/.local/lib/python3.6/site-packages/google_music_scripts/cli.py", line 618, in run
    args.func(args)
  File "/home/xxx/.local/lib/python3.6/site-packages/google_music_scripts/commands.py", line 374, in do_upload
    mm = google_music.musicmanager(args.username, uploader_id=args.uploader_id)
  File "/home/xxx/.local/lib/python3.6/site-packages/google_music/api.py", line 73, in musicmanager
    return MusicManager(username, uploader_id, token=token)
  File "/home/xxx/.local/lib/python3.6/site-packages/google_music/clients/musicmanager.py", line 49, in __init__
    if self.login(username, token=token):
  File "/home/xxx/.local/lib/python3.6/site-packages/google_music/clients/base.py", line 286, in login
    self._oauth()
  File "/home/xxx/.local/lib/python3.6/site-packages/google_music/clients/base.py", line 241, in _oauth
    self.session.refresh_token()
  File "/home/xxx/.local/lib/python3.6/site-packages/google_music/clients/base.py", line 123, in refresh_token
    withhold_token=True
  File "/home/xxx/.local/lib/python3.6/site-packages/google_music/clients/base.py", line 165, in request
    **kwargs
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/client.py", line 839, in request
    trust_env=trust_env,
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/client.py", line 870, in send
    async_response = concurrency_backend.run(coroutine, *args, **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/concurrency/asyncio.py", line 260, in run
    return self.loop.run_until_complete(coroutine(*args, **kwargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/client.py", line 265, in _get_response
    return await get_response(request)
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/middleware/basic_auth.py", line 19, in __call__
    return await get_response(request)
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/middleware/redirect.py", line 31, in __call__
    response = await get_response(request)
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/client.py", line 226, in get_response
    request, verify=verify, cert=cert, timeout=timeout
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/dispatch/proxy_http.py", line 245, in send
    request=request, verify=verify, cert=cert, timeout=timeout
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/dispatch/connection_pool.py", line 118, in send
    connection = await self.acquire_connection(origin=request.url.origin)
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/dispatch/proxy_http.py", line 97, in acquire_connection
    return await self.tunnel_connection(origin)
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/dispatch/proxy_http.py", line 115, in tunnel_connection
    await self.tunnel_start_tls(origin, connection)
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/dispatch/proxy_http.py", line 196, in tunnel_start_tls
    hostname=origin.host, ssl_context=ssl_context, timeout=timeout
  File "/home/xxx/.local/lib/python3.6/site-packages/httpx/concurrency/asyncio.py", line 63, in start_tls
    "asyncio.AbstractEventLoop.start_tls() is only available in Python 3.7+"
NotImplementedError: asyncio.AbstractEventLoop.start_tls() is only available in Python 3.7+

**Comment by thebigmunch** [comment] 2019-11-07 22:10
I've reported that issue to the library in question. It says it's Python 3.6+, but this piece of code in it doesn't follow that. We'll see what they have to say. Short of using Python 3.7 or 3.8, I don't have a short-term solution for you.

**Comment by fooeynet** [comment] 2019-11-07 22:28
Thanks for investigating!

**Comment by thebigmunch** [comment] 2019-11-08 10:19
I forgot another short-term alternative is to not use a proxy. None of these short-term options are very appropriate, though.

**Comment by thebigmunch** [comment] 2019-11-08 16:35
So, another alternative is to install uvloop. But for others. that only works on *nix.

From the discussion on httpx's issue tracker, it's looking like I will have to make my projects' only support Python 3.7+.

It is frustrating and flabbergasting, but they don't seem to see it as a problem for them to solve.

**Comment by fooeynet** [comment] 2019-11-08 18:30
Upgrading to 3.7 got me where I needed to be.
