### ISSUE TITLE
dependency incompatibility - might be causing upload issue

### ISSUE THREAD

**Issue by jrp13149** [thebigmunch/google-music-scripts#33] opened 2019-03-12 11:42 UTC
I'm having a problem with google play music losing the cd number on multidisc albums, I'm uploading flac files, and can confirm the correct meta data is in the flac file before upload, but the CD number is missing from the info of the tracks once uploaded. So on a two CD album, for example, the play order is two track 1s, then track 2s etc.

To start diagnosing I thought I'd upgrade to the latest set of google-music-scripts. In doing so, it threw a warning that I required **audio-metadata<0.4, >=0.3,** but I had 0.4 installed. So I uninstalled audio-metadata 0.4, and manually installed audio-metadata 0.3.4.

While doing so, I got three warnings. google-music-utils, google-music-scripts, and google-music-proto all require **audio-metadata<0.5, >=0.4**. Note that one of these previously wanted audio-metadata<0.4.

What is going on? Is it my general lack of familiarily with pip? I don't use this particular environment for anything other that google-music-scripts, so should I expect to see this sort of thing?

At time of writing, now attempting an upload using 4.0.1, hoping it will sort the metadata issue.

**Comment by jrp13149** [comment] 2019-03-12 11:44
I can confirm that my original upload metadata issue is fixed in 4.0.1.

**Comment by thebigmunch** [comment] 2019-03-12 15:23
For the record, this was caused by a copy/paste mistake in google-music-proto that I fixed in the 2.2.0 version of that package. Had nothing to do with audio- metadata.

**Closed by thebigmunch** 2019-03-12 15:23 UTC
